env:
  global:
    - CC_TEST_REPORTER_ID=186968cf5dfb3af465f3d7287e4280598b635441872f47bc1a09ff311fc5680b
language: ruby
rvm:
  - 2.5
before_install:
  - rvm install 2.6.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
